# Generated by Django 4.2.8 on 2024-08-08 06:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nameMenu', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('stt', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=True)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='menu.menu')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
