# Generated by Django 4.2.9 on 2024-06-13 01:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapRoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('root_name', models.CharField(default='Root', max_length=200)),
                ('number_order', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('number_order', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymap.maproot')),
            ],
        ),
    ]
