# Generated by Django 4.2.8 on 2024-06-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapchild',
            name='root_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapchild_set', to='mymap.maproot'),
        ),
    ]
