# Generated by Django 4.2.8 on 2024-08-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0002_alter_mapchild_root_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mapchild',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_mapchild_name'),
        ),
        migrations.AddConstraint(
            model_name='maproot',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_maproot_name'),
        ),
    ]
