# Generated by Django 4.2.8 on 2024-06-29 01:29

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('intent_name', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('action_name', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActionCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('num_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(
                    blank=True, default='', max_length=500)),
                ('language', models.CharField(choices=[
                 ('en', 'English'), ('vi', 'Tiếng Việt')], max_length=40)),
                ('intent_confidence', models.FloatField(default=0.2)),
                ('story_confidence', models.FloatField(default=0.2)),
                ('default_answer_low_conf', models.CharField(
                    default='Not understand/Bot không hiểu', max_length=200)),
                ('last_trained', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('num_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChitChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chithat',
                'verbose_name_plural': 'Chithats',
            },
        ),
        migrations.CreateModel(
            name='ChitChatIntentExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chithat Intent Example',
                'verbose_name_plural': 'Chithat Intent Examples',
            },
        ),
        migrations.CreateModel(
            name='ChitChatUtterExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chithat Utter Example',
                'verbose_name_plural': 'Chithat Utter Examples',
            },
        ),
        migrations.CreateModel(
            name='CustomAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('face_emotion', 'Biểu cảm khuôn mặt'), (
                    'touch_monitor', 'Màn hình bụng'), ('other_request', 'Action gọi ngoài')], default='', max_length=40)),
                ('action_save_name', models.CharField(default='', max_length=250)),
                ('show_fe_name', models.CharField(default='', max_length=250)),
                ('link_url', models.CharField(max_length=250, null=True)),
                ('image_icon', models.ImageField(
                    default='', upload_to='icon_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(
                    blank=True, default='', max_length=300)),
                ('extract_type', models.CharField(choices=[('duckling', 'Thực thể hệ thống'), (
                    'policy', 'Trích xuất theo tiên đoán')], default='policy', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='FormCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('num_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(
                    blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('num_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Vocabulary',
                'verbose_name_plural': 'Vocabularies',
            },
        ),
        migrations.CreateModel(
            name='TextCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
                ('num_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.step')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vocab', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.AddField(
            model_name='step',
            name='story',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.story'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('validate_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), (
                    'datetime', 'Datetime'), ('url', 'Url'), ('cmnd', 'CMND'), ('vn_phone_number', 'VN-PhoneNumber')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
                ('entity', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.entity')),
            ],
        ),
        migrations.CreateModel(
            name='JsonCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('num_order', models.IntegerField()),
                ('send_method', models.CharField(choices=[
                 ('POST', 'POST'), ('GET', 'GET')], max_length=40)),
                ('url', models.CharField(max_length=200)),
                ('headers', models.JSONField()),
                ('data', models.JSONField(null=True)),
                ('use_entity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.step')),
            ],
        ),
        migrations.CreateModel(
            name='IntentExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
                ('intent', models.ForeignKey(default=None, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='bot.intent')),
            ],
        ),
        migrations.AddField(
            model_name='intent',
            name='step',
            field=models.OneToOneField(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.step'),
        ),
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='bot_image_cards')),
                ('text', models.TextField(max_length=500)),
                ('num_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.step')),
            ],
        ),
        migrations.CreateModel(
            name='FormSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('utter_to_get_slot', models.TextField(max_length=300)),
                ('utter_again_if_not_valid', models.TextField(
                    default=None, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.formcard')),
                ('slot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.slot')),
            ],
        ),
        migrations.AddField(
            model_name='formcard',
            name='step',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.step'),
        ),
        migrations.CreateModel(
            name='EntityKeyWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=200)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bot.entity')),
                ('intent_example', models.ManyToManyField(to='bot.intentexample')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customaction',
            constraint=models.UniqueConstraint(
                fields=('action_save_name',), name='unique_custom_action'),
        ),
        migrations.AddField(
            model_name='chitchatutterexample',
            name='bot',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
        migrations.AddField(
            model_name='chitchatutterexample',
            name='chitchat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.chitchat'),
        ),
        migrations.AddField(
            model_name='chitchatintentexample',
            name='bot',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
        migrations.AddField(
            model_name='chitchatintentexample',
            name='chitchat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.chitchat'),
        ),
        migrations.AddField(
            model_name='chitchat',
            name='bot',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
        migrations.AddField(
            model_name='carouselcard',
            name='step',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.step'),
        ),
        migrations.AddField(
            model_name='button',
            name='image_card',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.imagecard'),
        ),
        migrations.AddField(
            model_name='button',
            name='payload',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.intent'),
        ),
        migrations.AddField(
            model_name='button',
            name='slot',
            field=models.ManyToManyField(to='bot.slot'),
        ),
        migrations.AddField(
            model_name='button',
            name='text_card',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.textcard'),
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.UniqueConstraint(
                fields=('account', 'name'), name='unique_bot_name'),
        ),
        migrations.AddField(
            model_name='actioncard',
            name='action',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.customaction'),
        ),
        migrations.AddField(
            model_name='actioncard',
            name='step',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bot.step'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(
                fields=('bot', 'word'), name='unique_vocab'),
        ),
        migrations.AddConstraint(
            model_name='textcard',
            constraint=models.UniqueConstraint(
                fields=('step', 'name'), name='unique_textcard_name'),
        ),
        migrations.AddConstraint(
            model_name='textcard',
            constraint=models.UniqueConstraint(
                fields=('step', 'num_order'), name='unique_textcard_order'),
        ),
        migrations.AddConstraint(
            model_name='synonym',
            constraint=models.UniqueConstraint(
                fields=('vocab', 'word'), name='unique_vocab_synonym'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(
                fields=('bot', 'name'), name='unique_story_name'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(
                fields=('story', 'name'), name='unique_step_name'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(
                fields=('story', 'num_order'), name='unique_step_order'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(
                fields=('bot', 'name'), name='unique_slot_name'),
        ),
        migrations.AddConstraint(
            model_name='jsoncard',
            constraint=models.UniqueConstraint(
                fields=('step', 'name'), name='unique_jsonapi_name'),
        ),
        migrations.AddConstraint(
            model_name='jsoncard',
            constraint=models.UniqueConstraint(
                fields=('step', 'num_order'), name='unique_jsonapi_order'),
        ),
        migrations.AddConstraint(
            model_name='intentexample',
            constraint=models.UniqueConstraint(
                fields=('intent', 'text'), name='unique_intent_example'),
        ),
        migrations.AddConstraint(
            model_name='intent',
            constraint=models.UniqueConstraint(
                fields=('bot', 'name'), name='unique_intent_name'),
        ),
        migrations.AddConstraint(
            model_name='imagecard',
            constraint=models.UniqueConstraint(
                fields=('step', 'name'), name='unique_imgcard_name'),
        ),
        migrations.AddConstraint(
            model_name='imagecard',
            constraint=models.UniqueConstraint(
                fields=('step', 'num_order'), name='unique_imgcard_order'),
        ),
        migrations.AddConstraint(
            model_name='formslot',
            constraint=models.UniqueConstraint(
                fields=('form', 'slot'), name='unique_formslot'),
        ),
        migrations.AddConstraint(
            model_name='formcard',
            constraint=models.UniqueConstraint(
                fields=('step', 'name'), name='unique_formcard_name'),
        ),
        migrations.AddConstraint(
            model_name='formcard',
            constraint=models.UniqueConstraint(
                fields=('step', 'num_order'), name='unique_formcard_order'),
        ),
        migrations.AddConstraint(
            model_name='entitykeyword',
            constraint=models.UniqueConstraint(
                fields=('entity', 'text'), name='unique_entity_key_word'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(
                fields=('bot', 'name'), name='unique_entity'),
        ),
        migrations.AddConstraint(
            model_name='chitchatutterexample',
            constraint=models.UniqueConstraint(
                fields=('chitchat', 'text'), name='unique_cc_utter_example'),
        ),
        migrations.AddConstraint(
            model_name='chitchatintentexample',
            constraint=models.UniqueConstraint(
                fields=('chitchat', 'text'), name='unique_cc_intent_example'),
        ),
        migrations.AddConstraint(
            model_name='chitchat',
            constraint=models.UniqueConstraint(
                fields=('bot', 'name'), name='unique_chitchat_name'),
        ),
        migrations.AddConstraint(
            model_name='carouselcard',
            constraint=models.UniqueConstraint(
                fields=('step', 'name'), name='unique_carouselcard_name'),
        ),
        migrations.AddConstraint(
            model_name='carouselcard',
            constraint=models.UniqueConstraint(
                fields=('step', 'num_order'), name='unique_carouselcard_order'),
        ),
        migrations.AddConstraint(
            model_name='actioncard',
            constraint=models.UniqueConstraint(
                fields=('step', 'name'), name='unique_action_card_name'),
        ),
        migrations.AddConstraint(
            model_name='actioncard',
            constraint=models.UniqueConstraint(
                fields=('step', 'num_order'), name='unique_action_card_order'),
        ),
    ]
