# Generated by Django 4.2.8 on 2024-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitykeyword',
            name='unique_entity_key_word',
        ),
        migrations.AddConstraint(
            model_name='entitykeyword',
            constraint=models.UniqueConstraint(fields=('entity', 'text'), name='unique_entity_text'),
        ),
    ]
