# Generated by Django 4.2.8 on 2024-07-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_entitykeyword_unique_entity_key_word_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitykeyword',
            name='unique_entity_text',
        ),
        migrations.AddConstraint(
            model_name='entitykeyword',
            constraint=models.UniqueConstraint(fields=('entity', 'text'), name='unique_entity_key_word'),
        ),
    ]
