# Generated by Django 4.2.8 on 2024-07-16 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_entitykeyword_unique_entity_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncard',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.customaction'),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='image',
            field=models.ImageField(blank=True, upload_to='bot_image_cards'),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='textcard',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
