# Generated by Django 4.2.8 on 2024-07-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_imagecard_text'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_step_name',
        ),
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_step_order',
        ),
    ]
