# Generated by Django 4.2.8 on 2024-07-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_step_unique_step_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitykeyword',
            name='unique_entity_key_word',
        ),
    ]
